version: '3'

dotenv: [ '.env' ]

tasks:
  build-push:
    desc: Build and push the Docker images to the Kubernetes cluster, restart the deployments
    cmds:
      - task: build-push-store
      - task: build-push-login
      - task: build-push-dashboard
      - task: build-push-admind
  build-push-store:
    cmds:
      - docker build -t ${DOCKER_REGISTRY}/kebe/store:latest -f build-aux/docker/Dockerfile.store .
      - docker push ${DOCKER_REGISTRY}/kebe/store:latest
  build-push-login:
    cmds:
      - docker build -t ${DOCKER_REGISTRY}/kebe/login:latest -f build-aux/docker/Dockerfile.login .
      - docker push ${DOCKER_REGISTRY}/kebe/login:latest
  build-push-dashboard:
    cmds:
      - docker build -t ${DOCKER_REGISTRY}/kebe/dashboard:latest -f build-aux/docker/Dockerfile.dashboard .
      - docker push ${DOCKER_REGISTRY}/kebe/dashboard:latest
  build-push-admind:
    cmds:
      - docker build -t ${DOCKER_REGISTRY}/kebe/admind:latest -f build-aux/docker/Dockerfile.admind .
      - docker push ${DOCKER_REGISTRY}/kebe/admind:latest
